export default function Policy() {
  return (
    <div className="policy-page">
      <div className="page-header">
        <h1 className="page-title">Privacy & <em>Terms</em></h1>
        <p className="page-subtitle">How we handle your data and the terms of using Job Intel</p>
      </div>

      <div className="policy-content">
        <section className="policy-section">
          <h2>Privacy Policy</h2>
          <p className="policy-updated">Last updated: March 2025</p>
          <p>
            Job Intel (“we”) is an AI-powered command center for your job alerts. We process alert data you receive via Distill.io webhooks to provide analysis, summaries, and suggested replies. Your data is processed on your own infrastructure when you self-host the application.
          </p>
          <h3>Data we process</h3>
          <ul>
            <li>Alert content (subject, body, source) that you send to the application</li>
            <li>Analysis results (summaries, scores, suggested replies) generated by AI</li>
            <li>Your preferences (e.g. theme) stored locally in your browser</li>
          </ul>
          <h3>Data retention & storage</h3>
          <p>
            When self-hosted, all data remains on your server. We do not transmit your alert content to third parties except to the AI provider (e.g. Anthropic) when you use analysis features. Review your AI provider’s privacy policy for their handling of submitted content.
          </p>
          <h3>Your rights</h3>
          <p>
            You can delete messages and data from the application. For self-hosted instances, you control retention and backups. If you use a hosted version, contact the operator for data deletion requests.
          </p>
        </section>

        <section className="policy-section">
          <h2>Terms of Use</h2>
          <p className="policy-updated">Last updated: March 2025</p>
          <p>
            By using Job Intel you agree to use it only for lawful purposes and in line with the terms of any AI services (e.g. Anthropic) that power the analysis. You are responsible for the accuracy of any replies or actions you take based on AI suggestions. We do not guarantee availability or specific results. We may update these terms; continued use after changes constitutes acceptance.
          </p>
        </section>

        <section className="policy-section">
          <h2>Contact</h2>
          <p>
            For questions about this policy or the application, please refer to the project repository or contact the operator of your instance.
          </p>
        </section>
      </div>
    </div>
  )
}
